#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEditor.U2D;
using UnityEngine;
using UnityEngine.U2D;

namespace BalloonFlow.EditorTools
{
    /// <summary>
    /// SpriteAtlas 들을 Addressable 그룹에 일괄 등록 + atlas 내부 sprite name 들을 Const.cs 에 자동 생성.
    ///
    /// 메뉴:
    ///   BalloonFlow > Addressables > Auto-Migrate Sprite Atlases
    ///
    /// 동작:
    ///   1) Assets/4.Atlas/*.spriteatlas 모두 Local_OnDemand 그룹 + "ui" 라벨 등록.
    ///      Address(key) = "atlas_<name>" (예: UI.spriteatlas → atlas_ui)
    ///   2) 각 atlas 의 sprite name 들 enumerate → Const.cs 에:
    ///      - ADDR_ATLAS_UI = "atlas_ui"
    ///      - SPR_ICON_HAND = "iconHand"  (sprite name 그대로)
    ///   3) 런타임 사용:
    ///      var sprite = await AddressableSystem.GetSpriteAsync(Const.ADDR_ATLAS_UI, Const.SPR_ICON_HAND);
    /// </summary>
    public static class AddressableAutoMigrate
    {
        private const string LOG_TAG = "[AddrMigrate]";
        // 그룹명은 AddressableSetupTool 의 상수와 일치
        private const string GROUP_LOCAL_ALWAYS = "Local_Always";
        private const string GROUP_LOCAL_DEMAND = "Local_OnDemand";
        private const string GROUP_REMOTE_CDM   = "Remote_CDM";
        private const string LABEL_UI = "ui";
        private const string ATLAS_FOLDER = "Assets/4.Atlas";
        private const string CONST_FILE = "Assets/1.Scripts/Core/Const.cs";

        private const string KEYS_REGION_BEGIN = "        #region Addressable Keys — TODO: 마이그레이션 진행하며 채워넣기";
        private const string KEYS_REGION_END = "        #endregion";

        private const string AUTOGEN_BEGIN = "        // ── AUTO-GENERATED by AddressableAutoMigrate (do not edit manually) ──";
        private const string AUTOGEN_END   = "        // ── /AUTO-GENERATED ──";

        [MenuItem("BalloonFlow/Addressables/Migrate All (Popup + UI + Prefabs + Sound + Material + Atlas)")]
        public static void MigrateAll()
        {
            AutoMigrateAtlases();
            MigratePopups();
            MigrateUI();
            MigrateInGamePrefabs();
            MigrateAudio();
            MigrateMaterials();
            RegenerateConstFromAllGroups();
            UnityEditor.EditorUtility.DisplayDialog("Addressables Migration",
                "전체 마이그레이션 완료. Const.cs 자동 갱신됨.\n" +
                "그룹: Local_Always (core), Local_OnDemand (ui), Remote_CDM (cdm)\n\n" +
                "예외 (Resources/ 잔존): UITitle.prefab, PopupError.prefab", "OK");
        }

        /// <summary>모든 BalloonFlow 그룹의 entry 를 Const.cs 자동 영역에 합쳐 기록.</summary>
        [MenuItem("BalloonFlow/Addressables/Regenerate Const Keys")]
        public static void RegenerateConstFromAllGroups()
        {
            var settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null) return;

            var sb = new StringBuilder();
            sb.AppendLine(AUTOGEN_BEGIN);
            sb.AppendLine("        // generated from Addressable groups Local_Always / Local_OnDemand / Remote_CDM");
            sb.AppendLine();

            // SpriteAtlas 영역은 별도로 한 번 더 (atlas 과 sprite name 구분)
            sb.AppendLine("        // ── Atlas keys ──────────────────────────────────");
            EmitGroupEntries(sb, settings, GROUP_LOCAL_DEMAND, e => e.address.StartsWith("atlas_"), "ADDR_");
            sb.AppendLine();

            sb.AppendLine("        // ── Atlas sprite names (UI atlas) ───────────────");
            // sprite 이름들은 atlas 등록 시 enumerate 했지만 Const 기록이 분산되므로 재실행 가독성 위해 atlas 별 enumerate
            EmitAtlasSpriteNames(sb, settings, GROUP_LOCAL_DEMAND);
            sb.AppendLine();

            sb.AppendLine("        // ── Popup keys ──────────────────────────────────");
            EmitGroupEntries(sb, settings, GROUP_LOCAL_DEMAND, e => e.address.StartsWith("popup_"), "ADDR_");
            sb.AppendLine();

            sb.AppendLine("        // ── UI keys ─────────────────────────────────────");
            EmitGroupEntries(sb, settings, GROUP_LOCAL_DEMAND, e => e.address.StartsWith("ui_"), "ADDR_");
            sb.AppendLine();

            sb.AppendLine("        // ── InGame Prefab keys (Local_Always / core) ────");
            EmitGroupEntries(sb, settings, GROUP_LOCAL_ALWAYS, e => e.address.StartsWith("prefab_"), "ADDR_");
            sb.AppendLine();

            sb.AppendLine("        // ── Audio keys (Remote_CDM / cdm) ───────────────");
            EmitGroupEntries(sb, settings, GROUP_REMOTE_CDM, e => e.address.StartsWith("audio_"), "ADDR_");
            sb.AppendLine();

            sb.AppendLine("        // 사용 예:");
            sb.AppendLine("        //   var prefab = await AddressableSystem.LoadAssetAsync<GameObject>(Const.ADDR_POPUP_PopupResult);");
            sb.AppendLine("        //   var clip   = await AddressableSystem.LoadAssetAsync<AudioClip>(Const.ADDR_AUDIO_Stage_Clear);");
            sb.AppendLine();
            sb.AppendLine(AUTOGEN_END);

            WriteConstBlock(sb.ToString());
            Debug.Log($"{LOG_TAG} ✔ Const.cs 통합 갱신 완료.");
        }

        private static void EmitGroupEntries(StringBuilder sb, AddressableAssetSettings settings,
            string groupName, System.Func<AddressableAssetEntry, bool> filter, string constPrefix)
        {
            var group = settings.FindGroup(groupName);
            if (group == null) return;
            var entries = group.entries.Where(filter).OrderBy(e => e.address).ToList();
            foreach (var e in entries)
            {
                string suffix = ToConstSuffix(e.address);
                sb.AppendLine($"        public const string {constPrefix}{suffix,-40} = \"{e.address}\";");
            }
        }

        private static void EmitAtlasSpriteNames(StringBuilder sb, AddressableAssetSettings settings, string groupName)
        {
            var group = settings.FindGroup(groupName);
            if (group == null) return;
            var atlasEntries = group.entries.Where(e => e.address.StartsWith("atlas_")).ToList();
            foreach (var entry in atlasEntries)
            {
                var atlas = AssetDatabase.LoadAssetAtPath<SpriteAtlas>(entry.AssetPath);
                if (atlas == null) continue;
                int count = atlas.spriteCount;
                if (count <= 0) continue;
                var sprites = new Sprite[count];
                atlas.GetSprites(sprites);
                var names = sprites.Where(s => s != null).Select(s => StripCloneSuffix(s.name)).Distinct().OrderBy(n => n);
                foreach (var name in names)
                {
                    string suffix = ToConstSuffix(name);
                    sb.AppendLine($"        public const string SPR_{suffix,-40} = \"{name}\";");
                }
            }
        }

        private static void WriteConstBlock(string newBlock)
        {
            string fullPath = Path.GetFullPath(CONST_FILE);
            if (!File.Exists(fullPath)) return;
            string content = File.ReadAllText(fullPath);

            int regionStart = content.IndexOf(KEYS_REGION_BEGIN);
            if (regionStart < 0) return;
            int regionEnd = content.IndexOf(KEYS_REGION_END, regionStart);
            if (regionEnd < 0) return;

            int contentStart = content.IndexOf('\n', regionStart) + 1;
            string before = content.Substring(0, contentStart);
            string after = content.Substring(regionEnd);
            File.WriteAllText(fullPath, before + newBlock + "\n" + after);
            AssetDatabase.Refresh();
        }

        // ────────────────────────────────────────────
        // 폴더 단위 일괄 등록
        // ────────────────────────────────────────────

        // KEEP: Resources/ 에 잔존시킬 asset 의 파일명 (확장자 제외)
        private static readonly HashSet<string> KEEP_IN_RESOURCES = new HashSet<string>
        {
            "UITitle",
            "PopupError",
        };

        [MenuItem("BalloonFlow/Addressables/Migrate Popups (except PopupError)")]
        public static void MigratePopups()
        {
            MigrateFolder("Assets/Resources/Popup", GROUP_LOCAL_DEMAND, LABEL_UI, "popup_");
        }

        [MenuItem("BalloonFlow/Addressables/Migrate UI (except UITitle)")]
        public static void MigrateUI()
        {
            MigrateFolder("Assets/Resources/UI", GROUP_LOCAL_DEMAND, LABEL_UI, "ui_");
        }

        [MenuItem("BalloonFlow/Addressables/Migrate InGame Prefabs (Balloon/Dart/Holder...)")]
        public static void MigrateInGamePrefabs()
        {
            // InGame 핵심은 Local_Always (core) — 게임 진입 즉시 사용, pool prewarm 대상
            MigrateFolder("Assets/Resources/Prefabs", GROUP_LOCAL_ALWAYS, "core", "prefab_");
        }

        [MenuItem("BalloonFlow/Addressables/Migrate Audio (BGM/SFX → Remote_CDM)")]
        public static void MigrateAudio()
        {
            // Audio 는 큼 + 빈도 낮은 변경 → Remote_CDM 후보. 일단 Local_OnDemand 도 옵션.
            // 정책: 6.Sound/ (Resources 밖) 의 모든 audio 를 Remote_CDM + cdm 라벨로
            MigrateFolder("Assets/6.Sound", GROUP_REMOTE_CDM, "cdm", "audio_");
        }

        [MenuItem("BalloonFlow/Addressables/Migrate Materials (3.Material → Local_OnDemand)")]
        public static void MigrateMaterials()
        {
            // Material 은 보통 prefab 의 dependency 로 자동 포함되지만,
            // 동적 swap 가능성 + 일관성 위해 Local_OnDemand 등록. ui 라벨 (UI 자체에 붙는 material 도 포함).
            MigrateFolder("Assets/3.Material", GROUP_LOCAL_DEMAND, LABEL_UI, "mat_");
        }

        /// <summary>
        /// 폴더 안의 모든 asset 을 그룹/라벨에 등록. KEEP_IN_RESOURCES 항목은 skip.
        /// Address(key) = constPrefix + filename (예: "popup_PopupResult", "audio_Stage_Clear")
        /// </summary>
        private static void MigrateFolder(string folder, string groupName, string label, string addressPrefix)
        {
            var settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null)
            {
                Debug.LogError($"{LOG_TAG} AddressableAssetSettings 없음. Setup Groups & Labels 먼저.");
                return;
            }
            var group = settings.FindGroup(groupName);
            if (group == null)
            {
                Debug.LogError($"{LOG_TAG} Group '{groupName}' 없음. Setup Groups & Labels 먼저.");
                return;
            }
            if (!settings.GetLabels().Contains(label)) settings.AddLabel(label);

            if (!System.IO.Directory.Exists(folder))
            {
                Debug.LogWarning($"{LOG_TAG} 폴더 없음: {folder}");
                return;
            }

            // 모든 asset (prefab + audio + 기타) — sprite/texture/material 은 의존성으로 자동 포함되므로 제외 권장
            var guids = AssetDatabase.FindAssets("", new[] { folder });
            int added = 0, skipped = 0;
            foreach (var guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (AssetDatabase.IsValidFolder(path)) continue;

                string fileName = Path.GetFileNameWithoutExtension(path);
                if (string.IsNullOrEmpty(fileName)) continue;

                // KEEP 항목 skip (Resources/ 잔존)
                if (KEEP_IN_RESOURCES.Contains(fileName))
                {
                    skipped++;
                    continue;
                }

                // 등록 대상 type 제한 — Prefab / AudioClip / SpriteAtlas / Texture(필요시) / Material
                var assetType = AssetDatabase.GetMainAssetTypeAtPath(path);
                if (assetType == null) continue;
                if (assetType == typeof(MonoScript) || assetType.Name == "DefaultAsset") continue;

                var entry = settings.CreateOrMoveEntry(guid, group, readOnly: false, postEvent: false);
                if (entry == null) continue;
                entry.SetAddress(addressPrefix + fileName, postEvent: false);
                if (!entry.labels.Contains(label)) entry.SetLabel(label, true, true);
                added++;
            }

            EditorUtility.SetDirty(settings);
            AssetDatabase.SaveAssets();
            Debug.Log($"{LOG_TAG} '{folder}' → {groupName}/{label}: 등록 {added}, KEEP-skip {skipped}");
        }

        [MenuItem("BalloonFlow/Addressables/Auto-Migrate Sprite Atlases")]
        public static void AutoMigrateAtlases()
        {
            var settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null)
            {
                Debug.LogError($"{LOG_TAG} AddressableAssetSettings 없음. 'Setup Groups & Labels' 먼저 실행.");
                return;
            }

            var group = settings.FindGroup(GROUP_LOCAL_DEMAND);
            if (group == null)
            {
                Debug.LogError($"{LOG_TAG} Group '{GROUP_LOCAL_DEMAND}' 없음. 'Setup Groups & Labels' 먼저 실행.");
                return;
            }

            if (!settings.GetLabels().Contains(LABEL_UI)) settings.AddLabel(LABEL_UI);

            // Atlas 들 찾기
            var atlasGuids = AssetDatabase.FindAssets("t:SpriteAtlas", new[] { ATLAS_FOLDER });
            if (atlasGuids.Length == 0)
            {
                Debug.LogWarning($"{LOG_TAG} {ATLAS_FOLDER} 에 SpriteAtlas 없음.");
                return;
            }

            // Editor 에서 atlas 들이 아직 pack 안 됐을 수 있음 → 강제 pack (build 시 수행되는 것과 동등)
            var atlasObjs = atlasGuids
                .Select(g => AssetDatabase.LoadAssetAtPath<SpriteAtlas>(AssetDatabase.GUIDToAssetPath(g)))
                .Where(a => a != null)
                .ToArray();
            if (atlasObjs.Length > 0)
            {
                SpriteAtlasUtility.PackAtlases(atlasObjs, EditorUserBuildSettings.activeBuildTarget, canCancel: false);
            }

            // 등록 + sprite name 수집
            var atlasInfos = new List<AtlasInfo>();
            foreach (var guid in atlasGuids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                string fileName = Path.GetFileNameWithoutExtension(path);
                string addr = "atlas_" + fileName.ToLowerInvariant();

                // Addressable 등록
                var entry = settings.CreateOrMoveEntry(guid, group, readOnly: false, postEvent: false);
                if (entry == null)
                {
                    Debug.LogWarning($"{LOG_TAG} entry 생성 실패: {path}");
                    continue;
                }
                entry.SetAddress(addr, postEvent: false);
                if (!entry.labels.Contains(LABEL_UI)) entry.SetLabel(LABEL_UI, true, true);

                // sprite name 수집 — pack 후 GetSprites 로 정확한 packed sprite 들. 그래도 0 이면 Packables 에서 fallback.
                var atlas = AssetDatabase.LoadAssetAtPath<SpriteAtlas>(path);
                if (atlas == null)
                {
                    Debug.LogWarning($"{LOG_TAG} atlas 로드 실패: {path}");
                    continue;
                }

                var spriteNames = new HashSet<string>();
                int packedCount = atlas.spriteCount;
                if (packedCount > 0)
                {
                    var sprites = new Sprite[packedCount];
                    atlas.GetSprites(sprites);
                    foreach (var s in sprites)
                        if (s != null) spriteNames.Add(StripCloneSuffix(s.name));
                }
                else
                {
                    // Pack 실패 / 빈 atlas → Packables (Object[] = 폴더/sprite/texture) 직접 탐색
                    var packables = atlas.GetPackables();
                    foreach (var p in packables)
                    {
                        if (p == null) continue;
                        string pPath = AssetDatabase.GetAssetPath(p);
                        if (string.IsNullOrEmpty(pPath)) continue;

                        if (AssetDatabase.IsValidFolder(pPath))
                        {
                            // 폴더 내부 모든 sprite
                            var sGuids = AssetDatabase.FindAssets("t:Sprite", new[] { pPath });
                            foreach (var sg in sGuids)
                            {
                                string sp = AssetDatabase.GUIDToAssetPath(sg);
                                var sub = AssetDatabase.LoadAllAssetsAtPath(sp);
                                foreach (var o in sub)
                                    if (o is Sprite spr) spriteNames.Add(StripCloneSuffix(spr.name));
                            }
                        }
                        else
                        {
                            var sub = AssetDatabase.LoadAllAssetsAtPath(pPath);
                            foreach (var o in sub)
                                if (o is Sprite spr) spriteNames.Add(StripCloneSuffix(spr.name));
                        }
                    }
                }

                var spriteList = spriteNames.OrderBy(n => n).ToList();
                atlasInfos.Add(new AtlasInfo
                {
                    atlasName = fileName,
                    addressableKey = addr,
                    spriteNames = spriteList
                });

                Debug.Log($"{LOG_TAG} '{fileName}.spriteatlas' 등록 — addr={addr}, sprites={spriteList.Count} (packed={packedCount})");
            }

            EditorUtility.SetDirty(settings);
            AssetDatabase.SaveAssets();

            // Const.cs 갱신
            UpdateConstFile(atlasInfos);
        }

        private static void UpdateConstFile(List<AtlasInfo> atlases)
        {
            string fullPath = Path.GetFullPath(CONST_FILE);
            if (!File.Exists(fullPath))
            {
                Debug.LogError($"{LOG_TAG} Const.cs 없음: {fullPath}");
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine(AUTOGEN_BEGIN);
            sb.AppendLine($"        // generated from {atlases.Count} SpriteAtlas(es) in {ATLAS_FOLDER}");
            sb.AppendLine();

            // Atlas key 들
            sb.AppendLine("        // SpriteAtlas Addressable keys");
            foreach (var a in atlases)
            {
                string constName = "ADDR_ATLAS_" + a.atlasName.ToUpperInvariant();
                sb.AppendLine($"        public const string {constName,-40} = \"{a.addressableKey}\";");
            }
            sb.AppendLine();

            // Sprite name 들 (atlas 별)
            foreach (var a in atlases)
            {
                sb.AppendLine($"        // Sprite names in '{a.atlasName}' atlas");
                foreach (var name in a.spriteNames)
                {
                    string constName = "SPR_" + ToConstSuffix(name);
                    sb.AppendLine($"        public const string {constName,-40} = \"{name}\";");
                }
                sb.AppendLine();
            }

            sb.AppendLine("        // 사용 예:");
            sb.AppendLine("        //   var spr = await AddressableSystem.GetSpriteAsync(Const.ADDR_ATLAS_UI, Const.SPR_ICONHAND);");
            sb.AppendLine();
            sb.AppendLine(AUTOGEN_END);

            string content = File.ReadAllText(fullPath);
            int regionStart = content.IndexOf(KEYS_REGION_BEGIN);
            if (regionStart < 0)
            {
                Debug.LogError($"{LOG_TAG} Const.cs 에 region 마커 없음: {KEYS_REGION_BEGIN}");
                return;
            }
            int regionEnd = content.IndexOf(KEYS_REGION_END, regionStart);
            if (regionEnd < 0)
            {
                Debug.LogError($"{LOG_TAG} region 종료 마커 없음.");
                return;
            }

            int contentStart = content.IndexOf('\n', regionStart) + 1;
            string before = content.Substring(0, contentStart);
            string after = content.Substring(regionEnd);

            string updated = before + sb.ToString() + "\n" + after;
            File.WriteAllText(fullPath, updated);
            AssetDatabase.Refresh();

            int totalSprites = atlases.Sum(a => a.spriteNames.Count);
            Debug.Log($"{LOG_TAG} ✔ Const.cs 갱신 — {atlases.Count} atlas + {totalSprites} sprite key 생성. " +
                      $"코드에서 'Const.SPR_ICONHAND' 처럼 사용.");
        }

        /// <summary>"iconHand(Clone)" → "iconHand"</summary>
        private static string StripCloneSuffix(string name)
        {
            int p = name.IndexOf('(');
            return p > 0 ? name.Substring(0, p).TrimEnd() : name;
        }

        /// <summary>"iconHand" → "ICONHAND", "iconHaptic_off" → "ICONHAPTIC_OFF"
        /// (단순 대문자화. snake_case 변환 시 충돌/혼동 방지 위해 그대로.)</summary>
        private static string ToConstSuffix(string name)
        {
            // 영숫자 + 언더스코어만 남기기
            var sb = new StringBuilder(name.Length);
            foreach (var c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_') sb.Append(char.ToUpperInvariant(c));
                else sb.Append('_');
            }
            return sb.ToString();
        }

        private struct AtlasInfo
        {
            public string atlasName;       // "UI"
            public string addressableKey;  // "atlas_ui"
            public List<string> spriteNames;
        }
    }
}
#endif
